// <auto-generated />
using System;
using InsumosAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsumosAPI.Migrations
{
    [DbContext(typeof(InsumosDBContext))]
    [Migration("20240801061115_DataDefault001")]
    partial class DataDefault001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsumosAPI.Entities.Cliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCliente"));

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            IdCliente = 1L,
                            Correo = "ana.rodriguez@example.com",
                            Direccion = "Av. Quito 123, Quito, Ecuador",
                            Estado = "A",
                            FechaCreacion = new DateTime(2024, 8, 1, 6, 11, 15, 0, DateTimeKind.Utc).AddTicks(4268),
                            Identificacion = "0998765432",
                            NombreCompleto = "Ana María Rodríguez",
                            Telefono = "+593987654321",
                            UsuarioCreacion = "SYSTEM"
                        },
                        new
                        {
                            IdCliente = 2L,
                            Correo = "carlos.fernandez@example.com",
                            Direccion = "Calle Guayaquil 456, Guayaquil, Ecuador",
                            Estado = "A",
                            FechaCreacion = new DateTime(2024, 8, 1, 6, 11, 15, 0, DateTimeKind.Utc).AddTicks(4270),
                            Identificacion = "0987654321",
                            NombreCompleto = "Carlos Fernández",
                            Telefono = "+593987654322",
                            UsuarioCreacion = "SYSTEM"
                        },
                        new
                        {
                            IdCliente = 3L,
                            Correo = "lucia.morales@example.com",
                            Direccion = "Av. Cuenca 789, Cuenca, Ecuador",
                            Estado = "A",
                            FechaCreacion = new DateTime(2024, 8, 1, 6, 11, 15, 0, DateTimeKind.Utc).AddTicks(4272),
                            Identificacion = "0976543210",
                            NombreCompleto = "Lucía Morales",
                            Telefono = "+593987654323",
                            UsuarioCreacion = "SYSTEM"
                        });
                });

            modelBuilder.Entity("InsumosAPI.Entities.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = 1L,
                            Apellidos = "Farmacia",
                            Contraseña = "12345",
                            Estado = "A",
                            FechaCreacion = new DateTime(2024, 8, 1, 6, 11, 15, 0, DateTimeKind.Utc).AddTicks(4027),
                            Identificacion = "0999999999",
                            Nombres = "Admin",
                            Rol = "Admin",
                            Username = "admin",
                            UsuarioCreacion = "SYSTEM"
                        },
                        new
                        {
                            IdUsuario = 2L,
                            Apellidos = "Orellana Maridueña",
                            Contraseña = "12345",
                            Estado = "A",
                            FechaCreacion = new DateTime(2024, 8, 1, 6, 11, 15, 0, DateTimeKind.Utc).AddTicks(4032),
                            Identificacion = "0955416755",
                            Nombres = "Milena Saray",
                            Rol = "Vendedor",
                            Username = "morella",
                            UsuarioCreacion = "SYSTEM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
